// Generated by https://quicktype.io

export interface PokemonListReponse {
  count: number;
  next: string;
  previous: string;
  results: BasicPokemonInfo[];
}

export interface BasicPokemonInfo {
  name: string;
  id: string;
  url: string;
}
